repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.19
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.392
    hooks:
      - id: pyright